/**
 * ABI → Elm UI module codegen.
 *
 * Reads one contract's verified bundle (`VerifiedBundle` from fetch.ts) and
 * emits an Elm module that renders every public function as a typed form
 * using `Web3.Ui.ContractRead` / `Web3.Ui.ContractWrite` / `Web3.Ui.AbiInput`
 * from `intrepidshape/elm-web3-ui`, plus a self-contained Model/Msg/update
 * pair that wires user clicks through to encoded port payloads.
 *
 * The generated module exposes:
 *   - Model        — record with input-buffer + status fields per function
 *   - init         — empty Model
 *   - Msg          — one variant per user action + per result
 *   - Intent       — NoIntent | DoCall E.Value | DoSend E.Value
 *   - update       — pure state transition + Intent describing port work
 *   - view         — composes ContractRead/ContractWrite forms
 *   - decodePortMsg — turns incoming JSON port data into a Msg
 *
 * Output is plain Elm a human could have written. Users fork and customise.
 */

import type { AbiItem, AbiParam, VerifiedBundle } from "./fetch.ts";

export interface GenerateOptions {
    readonly moduleName: string;           // e.g. "Generated.Views.Erc20"
    readonly contractsModule: string;      // e.g. "Generated.Contracts.Erc20" — typed wrappers from elm-web3 codegen
}

export function generateUiModule(
    bundle: VerifiedBundle,
    options: GenerateOptions,
): string {
    const fns = (bundle.abi ?? []).filter(isCallable);
    const reads = fns.filter(isRead);
    const writes = fns.filter(isWrite);

    return [
        renderModuleHeader(options.moduleName, options.contractsModule, bundle),
        renderImports(),
        renderModelType(fns),
        renderInit(fns),
        renderMsgType(fns),
        renderIntentType(),
        renderUpdate(fns),
        renderDecodePortMsg(fns),
        renderView(reads, writes),
        renderFieldDefs(fns),
        renderReadViews(reads),
        renderWriteViews(writes),
    ].join("\n\n\n");
}


// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

function isCallable(item: AbiItem): boolean {
    return item.type === "function" && typeof item.name === "string";
}

function isRead(item: AbiItem): boolean {
    return item.stateMutability === "view" || item.stateMutability === "pure";
}

function isWrite(item: AbiItem): boolean {
    return item.stateMutability === "nonpayable" || item.stateMutability === "payable";
}

function isPayable(item: AbiItem): boolean {
    return item.stateMutability === "payable";
}


// ---------------------------------------------------------------------------
// Name helpers — collision-safe
// ---------------------------------------------------------------------------

/**
 * Make a unique selector for a function within its module. Solidity allows
 * overloads (same name, different arg types) so we suffix `_N` when needed.
 */
function functionKey(fn: AbiItem, index: number, all: AbiItem[]): string {
    const name = fn.name ?? `fn${index}`;
    const collisions = all.filter((f) => f.name === name);
    if (collisions.length <= 1) return name;
    const ownIndex = collisions.indexOf(fn);
    return `${name}_${ownIndex}`;
}

function camel(s: string): string {
    return s.length === 0 ? s : s[0]!.toLowerCase() + s.slice(1);
}

function pascal(s: string): string {
    return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function ensureParamName(p: AbiParam, i: number): string {
    return p.name && p.name.length > 0 ? p.name : `arg${i}`;
}

function methodSignature(fn: AbiItem): string {
    const inputs = (fn.inputs ?? [])
        .map((p) => canonicalAbiType(p))
        .join(",");
    return `${fn.name}(${inputs})`;
}

function canonicalAbiType(p: AbiParam): string {
    if (p.type.startsWith("tuple")) {
        const inner = (p.components ?? []).map(canonicalAbiType).join(",");
        // tuple, tuple[], tuple[N] → (a,b,c), (a,b,c)[], (a,b,c)[N]
        const suffix = p.type.slice("tuple".length);
        return `(${inner})${suffix}`;
    }
    return p.type;
}


// ---------------------------------------------------------------------------
// Header / imports
// ---------------------------------------------------------------------------

function renderModuleHeader(
    moduleName: string,
    contractsModule: string,
    bundle: VerifiedBundle,
): string {
    return `module ${moduleName} exposing
    ( Model, init
    , Msg, Intent(..)
    , update, view
    , decodePortMsg
    )

{-| Auto-generated UI for **${bundle.contractName}** (\`${bundle.address}\` on chain ${bundle.chainId}).

Generated by \`@intrepidshape/dapp-gen\` from the verified Sourcify bundle.
Compiler: \`${bundle.compilerVersion}\`. Match kind: \`${bundle.matchKind}\`.

This is your code — edit it freely. Re-running \`dapp-gen\` will overwrite the
file unless you tell it not to. Typed wrappers live in
[\`${contractsModule}\`](${contractsModule}-).

@docs Model, init
@docs Msg, Intent
@docs update, view
@docs decodePortMsg

-}`;
}

function renderImports(): string {
    return `import Html exposing (Html)
import Html.Attributes as Attr
import Json.Decode as D
import Json.Encode as E
import Web3.Abi.Decode as AbiDecode
import Web3.Abi.Encode as AbiEncode
import Web3.BigInt as BigInt exposing (BigInt)
import Web3.Contract.Call as Call
import Web3.Contract.Send as Send
import Web3.Transaction as Tx
import Web3.Types as T
import Web3.Ui.AbiInput as AbiInput
import Web3.Ui.ContractRead as Read
import Web3.Ui.ContractWrite as Write`;
}


// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

function renderModelType(fns: AbiItem[]): string {
    const fields: string[] = [];

    fns.forEach((fn, idx) => {
        const key = functionKey(fn, idx, fns);
        const inputs = fn.inputs ?? [];

        for (const [i, p] of inputs.entries()) {
            const argName = ensureParamName(p, i);
            fields.push(`${camel(key)}_${argName} : AbiInput.Value`);
            fields.push(`${camel(key)}_${argName}_err : Maybe String`);
        }

        if (isRead(fn)) {
            fields.push(`${camel(key)}_status : Read.Status`);
        } else if (isWrite(fn)) {
            fields.push(`${camel(key)}_tx : Tx.Status`);
            if (isPayable(fn)) {
                fields.push(`${camel(key)}_value : String`);
            }
        }
    });

    if (fields.length === 0) {
        return `type alias Model =
    {}`;
    }

    return [
        `{-| Per-function input buffers, validation errors, and lifecycle state. -}`,
        `type alias Model =`,
        `    { ${fields[0]}`,
        ...fields.slice(1).map((f) => `    , ${f}`),
        `    }`,
    ].join("\n");
}

function renderInit(fns: AbiItem[]): string {
    const fields: string[] = [];

    fns.forEach((fn, idx) => {
        const key = functionKey(fn, idx, fns);
        const inputs = fn.inputs ?? [];

        for (const [i, p] of inputs.entries()) {
            const argName = ensureParamName(p, i);
            fields.push(`${camel(key)}_${argName} = AbiInput.initFor ${fieldDefName(key, argName)}`);
            fields.push(`${camel(key)}_${argName}_err = Nothing`);
        }

        if (isRead(fn)) {
            fields.push(`${camel(key)}_status = Read.Idle`);
        } else if (isWrite(fn)) {
            fields.push(`${camel(key)}_tx = Tx.Idle`);
            if (isPayable(fn)) {
                fields.push(`${camel(key)}_value = ""`);
            }
        }
    });

    if (fields.length === 0) {
        return `{-| Empty model. -}
init : Model
init =
    {}`;
    }

    return [
        `{-| Empty model with every input cleared. -}`,
        `init : Model`,
        `init =`,
        `    { ${fields[0]}`,
        ...fields.slice(1).map((f) => `    , ${f}`),
        `    }`,
    ].join("\n");
}


// ---------------------------------------------------------------------------
// Msg
// ---------------------------------------------------------------------------

function renderMsgType(fns: AbiItem[]): string {
    const variants: string[] = [];

    fns.forEach((fn, idx) => {
        const key = functionKey(fn, idx, fns);
        const ctor = pascal(key);
        const inputs = fn.inputs ?? [];

        for (const [i, p] of inputs.entries()) {
            const argName = ensureParamName(p, i);
            variants.push(`${ctor}${pascal(argName)}Changed AbiInput.Value`);
        }

        if (isRead(fn)) {
            variants.push(`${ctor}Read`);
            variants.push(`${ctor}Result (Result String String)`);
        } else if (isWrite(fn)) {
            if (isPayable(fn)) {
                variants.push(`${ctor}ValueChanged String`);
            }
            variants.push(`${ctor}Send`);
            variants.push(`${ctor}TxMsg Tx.Msg`);
        }
    });

    if (variants.length === 0) {
        return `{-| No callable functions. -}
type Msg
    = Noop`;
    }

    return [
        `{-| User actions and incoming results. -}`,
        `type Msg`,
        `    = ${variants[0]}`,
        ...variants.slice(1).map((v) => `    | ${v}`),
    ].join("\n");
}


// ---------------------------------------------------------------------------
// Intent
// ---------------------------------------------------------------------------

function renderIntentType(): string {
    return `{-| Side-effect description returned by [\`update\`](#update). The host
threads \`DoCall\` and \`DoSend\` payloads through its single \`web3Cmd\` port.
-}
type Intent
    = NoIntent
    | DoCall E.Value
    | DoSend E.Value`;
}


// ---------------------------------------------------------------------------
// update
// ---------------------------------------------------------------------------

function renderUpdate(fns: AbiItem[]): string {
    if (fns.length === 0) {
        return `{-| No-op update. -}
update : T.Address -> Msg -> Model -> ( Model, Intent )
update _ Noop model =
    ( model, NoIntent )`;
    }

    const branches: string[] = [];

    fns.forEach((fn, idx) => {
        const key = functionKey(fn, idx, fns);
        const ctor = pascal(key);
        const inputs = fn.inputs ?? [];
        const methodSig = methodSignature(fn);

        // …Changed branches
        for (const [i, p] of inputs.entries()) {
            const argName = ensureParamName(p, i);
            branches.push(
                [
                    `        ${ctor}${pascal(argName)}Changed v ->`,
                    `            ( { model | ${camel(key)}_${argName} = v, ${camel(key)}_${argName}_err = Nothing }, NoIntent )`,
                ].join("\n"),
            );
        }

        const argParseLines = inputs.map((p, i) => {
            const argName = ensureParamName(p, i);
            return `                Result.andThen
                    (\\xs ->
                        AbiInput.parse ${fieldDefName(key, argName)} model.${camel(key)}_${argName}
                            |> Result.map (\\x -> xs ++ [ x ])
                    )`;
        });

        const parseArgsExpr =
            inputs.length === 0
                ? `(Ok [])`
                : [`(Ok [])`, ...argParseLines].join("\n                    |> ");

        if (isRead(fn)) {
            const outDecoder = renderOutputDecoder(fn);
            branches.push(
                [
                    `        ${ctor}Read ->`,
                    `            case ${parseArgsExpr} of`,
                    `                Ok args ->`,
                    `                    ( { model | ${camel(key)}_status = Read.Pending }`,
                    `                    , DoCall`,
                    `                        (Call.encode`,
                    `                            (Call.readCall`,
                    `                                { contract = contract`,
                    `                                , method = "${methodSig}"`,
                    `                                , args = args`,
                    `                                , decoder = ${outDecoder}`,
                    `                                , id = "${callId(key)}"`,
                    `                                }`,
                    `                            )`,
                    `                        )`,
                    `                    )`,
                    `                Err err ->`,
                    `                    ( { model | ${camel(key)}_status = Read.Failed err }, NoIntent )`,
                ].join("\n"),
            );

            branches.push(
                [
                    `        ${ctor}Result res ->`,
                    `            case res of`,
                    `                Ok rendered ->`,
                    `                    ( { model | ${camel(key)}_status = Read.Success rendered }, NoIntent )`,
                    `                Err err ->`,
                    `                    ( { model | ${camel(key)}_status = Read.Failed err }, NoIntent )`,
                ].join("\n"),
            );
        } else if (isWrite(fn)) {
            if (isPayable(fn)) {
                branches.push(
                    [
                        `        ${ctor}ValueChanged v ->`,
                        `            ( { model | ${camel(key)}_value = v }, NoIntent )`,
                    ].join("\n"),
                );
            }

            const sendCall = isPayable(fn)
                ? [
                      `                            (Send.payableCall`,
                      `                                { contract = contract`,
                      `                                , method = "${methodSig}"`,
                      `                                , args = args`,
                      `                                , value = BigInt.fromString model.${camel(key)}_value |> Maybe.withDefault BigInt.zero`,
                      `                                }`,
                      `                            )`,
                  ].join("\n")
                : [
                      `                            (Send.writeCall`,
                      `                                { contract = contract`,
                      `                                , method = "${methodSig}"`,
                      `                                , args = args`,
                      `                                }`,
                      `                            )`,
                  ].join("\n");

            branches.push(
                [
                    `        ${ctor}Send ->`,
                    `            case ${parseArgsExpr} of`,
                    `                Ok args ->`,
                    `                    ( { model | ${camel(key)}_tx = Tx.AwaitingSignature }`,
                    `                    , DoSend`,
                    `                        (Send.encode`,
                    sendCall,
                    `                        )`,
                    `                    )`,
                    `                Err err ->`,
                    `                    ( { model | ${camel(key)}_tx = Tx.Failed err }, NoIntent )`,
                ].join("\n"),
            );

            branches.push(
                [
                    `        ${ctor}TxMsg txMsg ->`,
                    `            ( { model | ${camel(key)}_tx = Tx.update txMsg model.${camel(key)}_tx }, NoIntent )`,
                ].join("\n"),
            );
        }
    });

    return [
        `{-| Pure state transition + an [\`Intent\`](#Intent) describing any port work.`,
        ``,
        `\`contract\` is the deployed address the calls target; pass it in from your`,
        `app's Model so the same generated module can serve multiple deployments.`,
        `-}`,
        `update : T.Address -> Msg -> Model -> ( Model, Intent )`,
        `update contract msg model =`,
        `    case msg of`,
        branches.join("\n\n"),
    ].join("\n");
}

function callId(key: string): string {
    return `__gen_${key}`;
}


// ---------------------------------------------------------------------------
// decodePortMsg
// ---------------------------------------------------------------------------

function renderDecodePortMsg(fns: AbiItem[]): string {
    if (fns.length === 0) {
        return `{-| No port messages to decode. -}
decodePortMsg : D.Value -> Maybe Msg
decodePortMsg _ =
    Nothing`;
    }

    const readBranches = fns
        .filter(isRead)
        .map((fn) => {
            const idx = fns.indexOf(fn);
            const key = functionKey(fn, idx, fns);
            const ctor = pascal(key);
            return [
                `        "${callId(key)}" ->`,
                `            D.field "result" D.string`,
                `                |> D.map (\\s -> Just (${ctor}Result (Ok s)))`,
                `                |> orElseField`,
                `                    (D.field "error" D.string`,
                `                        |> D.map (\\e -> Just (${ctor}Result (Err e)))`,
                `                    )`,
            ].join("\n");
        })
        .join("\n\n");

    return [
        `{-| Route an incoming port-bound JSON value to a Msg, by matching its \`id\`.`,
        ``,
        `Returns \`Nothing\` for unrelated traffic (e.g. wallet events).`,
        `-}`,
        `decodePortMsg : D.Value -> Maybe Msg`,
        `decodePortMsg value =`,
        `    case D.decodeValue (D.field "id" D.string) value of`,
        `        Ok id ->`,
        `            case D.decodeValue (dispatcher id) value of`,
        `                Ok m ->`,
        `                    m`,
        ``,
        `                Err _ ->`,
        `                    Nothing`,
        ``,
        `        Err _ ->`,
        `            Nothing`,
        ``,
        ``,
        `dispatcher : String -> D.Decoder (Maybe Msg)`,
        `dispatcher id =`,
        `    case id of`,
        readBranches.length > 0 ? readBranches : `        _ ->\n            D.succeed Nothing`,
        ``,
        `        _ ->`,
        `            D.succeed Nothing`,
        ``,
        ``,
        `orElseField : D.Decoder a -> D.Decoder a -> D.Decoder a`,
        `orElseField fallback primary =`,
        `    D.oneOf [ primary, fallback ]`,
    ].join("\n");
}


// ---------------------------------------------------------------------------
// view
// ---------------------------------------------------------------------------

function renderView(reads: AbiItem[], writes: AbiItem[]): string {
    const all = [...reads, ...writes];
    const readItems = reads.map((fn) => {
        const idx = all.indexOf(fn);
        const key = functionKey(fn, idx, all);
        return `readView_${camel(key)} model`;
    });
    const writeItems = writes.map((fn) => {
        const idx = all.indexOf(fn);
        const key = functionKey(fn, idx, all);
        return `writeView_${camel(key)} contract explorerUrl model`;
    });

    if (readItems.length === 0 && writeItems.length === 0) {
        return `{-| Empty view — contract has no callable functions. -}
view : T.Address -> Maybe String -> Model -> Html Msg
view _ _ _ =
    Html.div [ Attr.class "generated-view generated-view--empty" ] []`;
    }

    const readsList = elmList(readItems, "            ");
    const writesList = elmList(writeItems, "            ");

    return [
        `{-| Render every callable function as a read or write card.`,
        ``,
        `\`contract\` is the target contract address. \`explorerUrl\` is an optional`,
        `block-explorer URL prefix for tx-hash links (\`Nothing\` = local dev).`,
        `-}`,
        `view : T.Address -> Maybe String -> Model -> Html Msg`,
        `view contract explorerUrl model =`,
        `    Html.div [ Attr.class "generated-view" ]`,
        `        [ Html.div [ Attr.class "generated-view__section generated-view__section--reads" ]`,
        `            ${readsList}`,
        `        , Html.div [ Attr.class "generated-view__section generated-view__section--writes" ]`,
        `            ${writesList}`,
        `        ]`,
    ].join("\n");
}

/** Render an Elm list literal, one element per line, comma-leading style. */
function elmList(items: string[], indent: string): string {
    if (items.length === 0) return "[]";
    if (items.length === 1) return `[ ${items[0]} ]`;
    const first = items[0]!;
    const rest = items.slice(1).map((i) => `, ${i}`).join(`\n${indent}`);
    return `[ ${first}\n${indent}${rest}\n${indent}]`;
}


// ---------------------------------------------------------------------------
// Field defs
// ---------------------------------------------------------------------------

function fieldDefName(key: string, argName: string): string {
    return `${camel(key)}_${argName}_field`;
}

function renderFieldDefs(fns: AbiItem[]): string {
    const defs: string[] = [];
    fns.forEach((fn, idx) => {
        const key = functionKey(fn, idx, fns);
        const inputs = fn.inputs ?? [];
        for (const [i, p] of inputs.entries()) {
            const argName = ensureParamName(p, i);
            defs.push(`${fieldDefName(key, argName)} : AbiInput.Field
${fieldDefName(key, argName)} =
    ${fieldExpr(p, argName)}`);
        }
    });
    if (defs.length === 0) {
        return `-- (no input fields)`;
    }
    return `-- INPUT FIELD DEFINITIONS --------------------------------------------------\n\n\n${defs.join("\n\n\n")}`;
}

function fieldExpr(p: AbiParam, displayName: string): string {
    if (p.type.startsWith("tuple")) {
        const children = (p.components ?? []).map((cp, i) =>
            fieldExpr(cp, ensureParamName(cp, i)),
        );
        const childrenText =
            children.length === 0
                ? `[]`
                : `[ ${children.join("\n                , ")}\n                ]`;
        return `AbiInput.field
        { name = "${displayName}"
        , solType = "${p.type}"
        , children =
            ${childrenText.replace(/\n/g, "\n            ")}
        }`;
    }
    return `AbiInput.field { name = "${displayName}", solType = "${p.type}", children = [] }`;
}


// ---------------------------------------------------------------------------
// Read views
// ---------------------------------------------------------------------------

function renderReadViews(reads: AbiItem[]): string {
    if (reads.length === 0) return `-- (no read functions)`;
    const blocks = reads.map((fn) => {
        const idx = reads.indexOf(fn);
        const key = functionKey(fn, idx, reads);
        const argConfigs = (fn.inputs ?? []).map((p, i) => {
            const argName = ensureParamName(p, i);
            return [
                `            { field = ${fieldDefName(key, argName)}`,
                `            , value = model.${camel(key)}_${argName}`,
                `            , onChange = ${pascal(key)}${pascal(argName)}Changed`,
                `            , error = model.${camel(key)}_${argName}_err`,
                `            }`,
            ].join("\n");
        });

        const argsBody =
            argConfigs.length === 0
                ? `        , args = []`
                : [
                      `        , args =`,
                      `            [ ${argConfigs[0]?.trimStart()}`,
                      ...argConfigs.slice(1).map((c) => `            , ${c.trimStart()}`),
                      `            ]`,
                  ].join("\n");

        const returnLabel = renderReturnLabel(fn);

        return `readView_${camel(key)} : Model -> Html Msg
readView_${camel(key)} model =
    Read.view []
        { name = "${fn.name}"
        , solType = "${returnLabel}"
${argsBody}
        , status = model.${camel(key)}_status
        , onRead = ${pascal(key)}Read
        , readLabel = "Read"
        }`;
    });
    return `-- READ VIEWS -----------------------------------------------------------------\n\n\n${blocks.join("\n\n\n")}`;
}

function renderReturnLabel(fn: AbiItem): string {
    const outs = fn.outputs ?? [];
    if (outs.length === 0) return "()";
    if (outs.length === 1) return outs[0]!.type;
    return `(${outs.map((o) => o.type).join(", ")})`;
}


// ---------------------------------------------------------------------------
// Write views
// ---------------------------------------------------------------------------

function renderWriteViews(writes: AbiItem[]): string {
    if (writes.length === 0) return `-- (no write functions)`;
    const blocks = writes.map((fn) => {
        const idx = writes.indexOf(fn);
        const key = functionKey(fn, idx, writes);
        const argConfigs = (fn.inputs ?? []).map((p, i) => {
            const argName = ensureParamName(p, i);
            return [
                `            { field = ${fieldDefName(key, argName)}`,
                `            , value = model.${camel(key)}_${argName}`,
                `            , onChange = ${pascal(key)}${pascal(argName)}Changed`,
                `            , error = model.${camel(key)}_${argName}_err`,
                `            }`,
            ].join("\n");
        });

        const argsBody =
            argConfigs.length === 0
                ? `        , args = []`
                : [
                      `        , args =`,
                      `            [ ${argConfigs[0]?.trimStart()}`,
                      ...argConfigs.slice(1).map((c) => `            , ${c.trimStart()}`),
                      `            ]`,
                  ].join("\n");

        const payableBody = isPayable(fn)
            ? [
                  `        , payable =`,
                  `            Just`,
                  `                { value = model.${camel(key)}_value`,
                  `                , onValueChange = ${pascal(key)}ValueChanged`,
                  `                , valid = True`,
                  `                }`,
              ].join("\n")
            : `        , payable = Nothing`;

        const label = pascal(fn.name ?? key);
        const pendingLabel = `${label}…`;

        return `writeView_${camel(key)} : T.Address -> Maybe String -> Model -> Html Msg
writeView_${camel(key)} _ explorerUrl model =
    Write.view []
        { name = "${fn.name}"
${argsBody}
${payableBody}
        , txStatus = model.${camel(key)}_tx
        , onSend = ${pascal(key)}Send
        , sendLabel = "${label}"
        , pendingLabel = "${pendingLabel}"
        , explorerUrl = explorerUrl
        }`;
    });
    return `-- WRITE VIEWS ----------------------------------------------------------------\n\n\n${blocks.join("\n\n\n")}`;
}


// ---------------------------------------------------------------------------
// Output decoders
// ---------------------------------------------------------------------------

/**
 * Render a `D.Decoder String` that decodes the ABI return value as a
 * human-readable string. For multi-output functions we render a JSON-ish
 * concatenation. The Tier-1 ContractRead displays this string as-is in its
 * Success state; users are expected to swap in their own pretty-printer once
 * they fork the generated code.
 */
function renderOutputDecoder(fn: AbiItem): string {
    const outs = fn.outputs ?? [];
    if (outs.length === 0) {
        return `D.succeed "()"`;
    }
    if (outs.length === 1) {
        return scalarOutputDecoder(outs[0]!);
    }
    // Multi-output: render each then join with " | "
    return `D.map (\\xs -> "(" ++ String.join ", " xs ++ ")") (D.list D.string)`;
}

function scalarOutputDecoder(p: AbiParam): string {
    if (p.type === "address") {
        return `D.map T.addressToString AbiDecode.address`;
    }
    if (p.type === "bool") {
        return `D.map (\\b -> if b then "true" else "false") AbiDecode.bool`;
    }
    if (p.type === "string") {
        return `AbiDecode.string`;
    }
    if (p.type.startsWith("uint")) {
        return `D.map BigInt.toString AbiDecode.uint256`;
    }
    if (p.type.startsWith("int")) {
        return `D.map BigInt.toString AbiDecode.int256`;
    }
    if (p.type === "bytes32") {
        return `AbiDecode.bytes32`;
    }
    // dynamic bytes / arrays / tuples — Phase 1 returns raw hex string the
    // port handler put in `result`. The user can swap in a richer decoder
    // when they fork the generated module.
    return `D.string`;
}
